# Generated by Django 2.2.4 on 2019-08-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.IntegerField(primary_key=True, serialize=False)),
                ('level', models.CharField(max_length=10, null=True)),
                ('house_no', models.CharField(max_length=50, null=True)),
                ('street_name', models.CharField(max_length=100)),
                ('area_name', models.CharField(max_length=100)),
                ('postal_code', models.IntegerField()),
                ('district', models.CharField(max_length=100)),
                ('long', models.DecimalField(decimal_places=3, max_digits=8)),
                ('lat', models.DecimalField(decimal_places=3, max_digits=8)),
            ],
        ),
    ]
