# Generated by Django 2.2.4 on 2019-08-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_fb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
